services:
    application:
        build: .
        ports:
            - 80:80
        volumes:
            - .:/var/www
        depends_on:
            - database
        links:
                - database

    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        networks:
            - trafegus-test

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - database
        environment:
            PMA_HOST: database
            UPLOAD_LIMIT: 512M
            MEMORY_LIMIT: 512M
        ports:
            - 8080:80
        depends_on:
            - database
        networks:
            - trafegus-test

networks:
  trafegus-test:
    driver: bridge