version: "3.8"

services:
    application:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www
        depends_on:
            - database
        networks:
            - trafegus-test
        command: >
            /bin/bash -c "
            dockerize -wait tcp://database:3306 -timeout 60s &&
            composer install --no-scripts --prefer-dist &&
            php vendor/bin/doctrine-migrations migrate --no-interaction &&
            apache2-foreground
            "

    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - trafegus-test
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
            interval: 10s
            retries: 5
            start_period: 10s
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: database
            UPLOAD_LIMIT: 512M
            MEMORY_LIMIT: 512M
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - trafegus-test

volumes:
    mysql_data:
        driver: local

networks:
    trafegus-test:
        driver: bridge
