version: "3.8"

services:
    application:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www
        depends_on:
            - database
        networks:
            - trafegus-test
        command: /bin/bash -c "composer install --no-scripts --prefer-dist && apache2-foreground"

    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        volumes:
            - mysql_data:/var/lib/mysql
            - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
        networks:
            - trafegus-test

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: database
            UPLOAD_LIMIT: 512M
            MEMORY_LIMIT: 512M
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - trafegus-test

volumes:
    mysql_data:
        driver: local

networks:
    trafegus-test:
        driver: bridge
