<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h2 class="m-0">Listagem de Motoristas</h2>
        <a href="<?= $this->url('driver', ['action' => 'create']); ?>" class="btn btn-primary">Adicionar Motorista</a>
    </div>
    <div class="card-body">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Nome</th>
                <th>RG</th>
                <th>CPF</th>
                <th>Telefone</th>
                <th>Veículo</th>
                <th></th>
            </tr>
            <?php foreach ($drivers as $driver): ?>
                <tr>
                    <td><?= $driver->getName(); ?></td>
                    <td><?= $driver->getRg(); ?></td>
                    <td><?= $driver->getCpf(); ?></td>
                    <td><?= $driver->getPhone(); ?></td>
                    <td>
                        <a href="<?= $this->url('vehicle', ['action' => 'update', 'id' => $driver->getVehicle()->getId()]); ?>">
                            <?= $driver->getVehicle()->getLicensePlate() ?>
                        </a>
                    </td>
                    <td class="text-center">
                        <a class="btn btn-outline-warning" href="<?= $this->url('driver', ['action' => 'update', 'id' => $driver->getId()]); ?>">
                            <i class="fas fa-pencil-alt"></i> Editar
                        </a>
                        <a class="btn btn-outline-danger" onclick="return confirm('Deseja realmente excluir esse motorista?')" href="<?= $this->url('driver', ['action' => 'delete', 'id' => $driver->getId()]); ?>">
                            <i class="fas fa-trash"></i> Excluir
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>