<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h2 class="m-0">Listagem de Veículos</h2>
        <a href="<?= $this->url('vehicle', ['action' => 'create']); ?>" class="btn btn-primary">Adicionar Veículo</a>
    </div>
    <div class="card-body">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Placa</th>
                <th>Renavam</th>
                <th>Modelo</th>
                <th>Marca</th>
                <th>Ano</th>
                <th>Cor</th>
                <th></th>
            </tr>
            <?php foreach ($vehicles as $vehicle): ?>
                <tr>
                    <td><?= $vehicle->getLicensePlate(); ?></td>
                    <td><?= $vehicle->getRenavam(); ?></td>
                    <td><?= $vehicle->getModel(); ?></td>
                    <td><?= $vehicle->getBrand(); ?></td>
                    <td><?= $vehicle->getYear(); ?></td>
                    <td><?= $vehicle->getColor(); ?></td>
                    <td class="text-center">
                        <a class="btn btn-outline-warning" href="<?= $this->url('vehicle', ['action' => 'update', 'id' => $vehicle->getId()]); ?>">
                            <i class="fas fa-pencil-alt"></i> Editar
                        </a>
                        <a class="btn btn-outline-danger" onclick="return confirm('Deseja realmente excluir esse motorista?')" href="<?= $this->url('vehicle', ['action' => 'delete', 'id' => $vehicle->getId()]); ?>">
                            <i class="fas fa-trash"></i> Excluir
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>