<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Test Trafegus')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.png'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/fontawesome.min.css'))
        ->prependStylesheet($this->basePath('css/fontawesome-all.min.css'))
        ->prependStylesheet($this->basePath('css/select2.min.css'))
        ->appendStylesheet($this->basePath('css/select2-bootstrap-5-theme.min.css')) ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <nav class="navbar navbar-expand-md bg-light bg-light mb-4" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/logo.svg') ?>" alt="Laminas">
                <span class="navbar-text text-light">MVC Skeleton</span>
            </a>
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="fa-solid fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a
                            class="nav-link"
                            aria-current="page"
                            href="<?= $this->url('home') ?>">Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                            class="nav-link"
                            aria-current="page"
                            href="<?= $this->url('vehicle') ?>">Veículos
                        </a>
                    </li>
                    <li class="nav-item">
                        <a
                            class="nav-link"
                            aria-current="page"
                            href="<?= $this->url('driver') ?>">Motoristas
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?>
            </p>
        </footer>
    </div>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->appendFile($this->basePath('js/jquery.mask.min.js'))
        ->appendFile($this->basePath('js/main.js'))
        ->appendFile($this->basePath('js/select2.min.js')) ?>
</body>

</html>