<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="row">
    <div class="col-md-6">
        <div class="card text-white bg-primary mb-3">
            <div class="card-header">Motoristas</div>
            <div class="card-body">
                <h5 class="card-title d-flex justify-content-between align-items-center">
                    <span>Total de Motoristas</span>
                    <i class="fs-1 fa-regular fa-id-card"></i>
                </h5>
                <p class="card-text fs-3" id="motoristas-count"><?= $countDrivers ?></p>
                <div class="d-grid gap-2">
                    <a href="<?= $this->url('driver') ?>" class="btn btn-light">Ver Motoristas</a>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card text-white bg-success mb-3">
            <div class="card-header">Veículos</div>
            <div class="card-body">
                <h5 class="card-title d-flex justify-content-between align-items-center">
                    <span>Total de Veículos</span>
                    <i class="fs-1 fa-solid fa-truck"></i>
                </h5>
                <p class="card-text fs-3" id="veiculos-count"><?= $countVehicles ?></p>
                <div class="d-grid gap-2">
                    <a href="<?= $this->url('vehicle') ?>" class="btn btn-light">Ver Veículos</a>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="card text-whitemb-3">
            <div class="card-body">
                <div id="load-map"></div>
            </div>
        </div>
    </div>
</div>